---
- hosts: all
  become: true
  pre_tasks:

  - name: Install Updates (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"


- hosts: ubuntu_server
  become: true
  roles:
    - Neutron
    - Horizon
    - Cinder
